### ISSUE TITLE
Design for unity

### ISSUE THREAD

**Issue by dtylman** [yanablack/GameOfLife#2]
See the rules here: https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life

My idea is to create a Prefab and a basic script for each living creature. 
A script will implement the game-of-life rules. Need to discuss how to make the game-of-life rules script.

Lets have the following limitation at start:

- The basic scene has only a simple plain (floor)
- We are using physics
- Each `creature` is a cube. 
- Creatures lives and dies on plain, they do not overlap or expand to the height.
- A neighbor creature is a creature that is near-by. 

Since creatures are cubical, we can only have 4 neighbors

**Comment by dtylman** [comment]
- [ ] write a static function that gets a creature (or position) and counts its neighbors. use `Physics.OverlapSphere` 

- [ ] use `Time.deltatime` to calculate an interval in the `FixedUpdate` method of the `creature` script to count number of neigbors and act accordingly.

- [ ] create an empty `GameObject` to manage the scene. Attach a script to it, this script will: (a) initialize the scene with creatures at random positions (b) will create new-born creatures in places.

**Comment by yanablack** [comment]
So there's no need for a grid/matrix?

**Comment by dtylman** [comment]
don't think so
