### ISSUE TITLE
Randomally spawn creatures at startup

### ISSUE THREAD

**Issue by dtylman** [yanablack/GameOfLife#4]
When the scene starts, spawn creatures randomly:

- Create empty GameObject on scene, name it `SceneManager` or something like that.
- Add a script to that GameObject, override its `start` method and use Instantiate to spawn some creatures on the plain.

**Comment by yanablack** [comment]
Can I ask newbie questions here as well? 
If so, I don't quite fully understand how do I decide where to declare a variable - outside or within a function? Can I do one of the two even if I use the variable only in the context of the function?
